config/routes.rb
Blogger::Application.routes.draw do
  root to: 'articles#index'
  resources :articles do
  resources :comments

end
  resources :tags
  resources :authors
  resources :author_sessions, only: [ :new, :create, :destroy ]
  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :author
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings

	has_many :featured


	has_attached_file :image,
	:path => "images/:style/:id/:filename"    
        
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
 

   def tag_list
       tags.join(", ")
    end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end
 end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :articles
  validates_confirmation_of :password, message: "should match confirmation", if: :password



end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/featured.rb
class Featured < ActiveRecord::Base
	belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

include ArticlesHelper

def new
   @article = Article.new
end

def index
	@articles = Article.all
  @tag = Tag.all
end

def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id

end

 

   def create
        @article = Article.new(article_params)
        @article.save
       

        flash.notice = "Article '#{@article.title}' Posted!"
        redirect_to article_path(@article)
  end



  def destroy
  	 @article = Article.find(params[:id])
  	 @article.destroy

  	 redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated!"

     redirect_to article_path(@article)
  end

  def user_params
  params.require(:user).permit(:image)
  end

  
end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
	 def new
  end

  def create
    if login(params[:email], params[:password])
      redirect_back_or_to(articles_path, message: 'Logged in successfully.')
    else
      flash.now.alert = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, message: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]

def zero_authors_or_authenticated
  unless Author.count == 0 || current_user
    redirect_to root_path
    return false
  end
end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
    @authors =Author.find(:all, :order => 'name')
  end

  # GET /authors/1/edit
  def edit
    
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
      @comment = Comment.new(comment_params)
      @comment.article_id = params[:article_id]

      @comment.save

      redirect_to article_path(@comment.article)
    end

    def comment_params
       params.require(:comment).permit(:author_name, :body)
    end
    end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
    @tag = Tag.find(params[:id])
  end
  def index
      @tag = Tag.all
  end

 def destroy
  	 @tag = Tag.find(params[:id])
  	 @tag.destroy

  	 redirect_to articles_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
   def article_params
	   params.require(:article).permit(:title, :body, :tag_list, :image)
   end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>

</div>

app/views/articles/_form.html.erb
<div class="row">
 
     
    <div class="large-9 columns" role="content">


<%= form_for(@article, html: {multipart: true}) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <div class="row">
      <div class="large-6 columns">
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
  <%= f.label :tag_list %><br />
  <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
  <% if @article.image.exists? %>
      <%= image_tag @article.image.url %><br/>
  <% end %>
  <%= f.label :image, "Attach a New Image" %><br />
  <%= f.file_field :image %>

  
</p>
  <p>
    <%= f.submit %>
  </p>
  </ul>
 </div>
<% end %>

app/views/articles/edit.html.erb
<div class="row">
 
     
    <div class="large-9 columns" role="content">

<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
 <div class="row">
    <div class="large-12 columns">
      <div class="nav-bar right">
       <ul class="button-group">
         <li><%= link_to 'Log in', login_path, :class => " button"  %></li>
         <li><%= link_to 'Authors', authors_path, :class => " button"  %></li>
         <li><%= link_to 'My Resume', "http://resume-alpha.michaelrwiss.com/", :class => "button"%></li>
        </ul>
      </div>
      <h1 class="title">Food Blog <!--<small>This is my blog. </small>--></h1>
      <%= link_to "Create a New Article", new_article_path, class: "new_article" %>
      <hr/>
    </div>
  </div>

<ul id="articles">
  <% @articles.each do |article| %>
    


 
</ul>


 
 
 
 
   
 
 
   
 
  <div class="row">
 
     
    <div class="large-9 columns" role="content">
 
      <article>
 
        <h2><%= link_to article.title, article_path(article), class: 'article_title' %></a></h2>
        <%= link_to "Create a New Article", new_article_path, class: "new_article" %>
        <!--<h6>Written by <a href="#">John Smith</a> on August 12, 2012.</h6>-->
        <h3>Written by <%= article.author %> </h3>
      
       
 
        <div class="row">
          <div class="large-6 columns">
           <!-- <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa.</p>
            <p>Boudin aliqua adipisicing rump corned beef. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p> -->
          </div>
          <div class="large-6 columns">
            <%= image_tag article.image.url %>
          </div>
        </div>
 
        <!-- <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
 
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p> -->

      <p><%= article.body %></p>

 
      </article>
 
      <hr/>
 
 
    </div>
 
     
 
 
     
 
    <aside class="large-3 columns">
 
      <h5>Categories</h5>
      <ul id="tags">
  <% @tag.each do |tag| %>
    <li>
    <%= link_to tag.name, tag_path(tag) %>
    &nbsp
    <em><%= link_to "delete", tag_path(tag), :method => :delete %></em>
    </li>
  <% end %>
</ul>
 
      
 
    </aside>
 
     
  </div>
 
   
  <% end %>
 
   
 
  <footer class="row">
    <div class="large-12 columns">
      <hr/>
      <div class="row">
        <div class="large-6 columns">
          <p>© Copyright Michael Wiss.</p>
        </div>
        
      </div>
    </div>
  </footer>
  

app/views/articles/new.html.erb
<div class="row">
 
     
    <div class="large-9 columns" role="content">

<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
 <div class="row">
 
     
    <div class="large-9 columns" role="content">
 
   
 


<h1><%= @article.title %></h1>
 <p>
  Tags:
  <% @article.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<div class="row">
      <div class="large-6 columns">

        <p><%= image_tag @article.image.url %></p>
        <p><%= @article.body %></p>
 
<ul>
  <li><%= link_to "edit", edit_article_path(@article) %></li>
  <li><%= link_to "delete", article_path(@article), method: :delete,  data: {confirm: "Really delete the article?"}%></li>

  

  <h3>Comments (<%= @article.comments.size %>)</h3>
  <%= render partial: 'articles/comment', collection: @article.comments %>

  <%= render partial: 'comments/form' %>
  <li><%= link_to "<< Back to Articles List", articles_path %></li>
 </ul>

app/views/author_sessions/new.html.erb
<div class="row">
 
     
    <div class="large-9 columns" role="content">

<h1>Login</h1>

<%= form_tag author_sessions_path, method: :post do %>
  <div class="field">
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br/>
  </div>
  <div class="field">
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br/>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/authors/edit.html.erb
<div class="row">
 
     
    <div class="large-9 columns" role="content">


<h1>Editing author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<div class="row">
 
     
    <div class="large-9 columns" role="content">


<h1>Listing authors</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<div class="row">
 
     
    <div class="large-9 columns" role="content">

<h1>New author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<div class="row">
 
     
    <div class="large-9 columns" role="content">

<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>



<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :author_name, "Your Name"  %><br/>
    <%= f.text_field :author_name %>
  </p>
  <p>
    <%= f.label :body, "Your comment" %><br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit 'Submit' %>
  </p>
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box success <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
   
   <!--<div data-alert class="alert-box">
  
    
   <%= flash.notice %>
   <a href="#" class="close">&times;</a>-->

   <%= render 'layouts/messages' %>
  
   
   
</div>

    <%= yield %>
    <hr>
      <h6>
        <% if logged_in? %>
          <%= "Logged in as #{current_user.email}" %>
          <%= link_to "(logout)", logout_path %>
        <% else %>
          <%= link_to "(login)", login_path %>
        <% end %>
        </h6>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tags/index.html.erb
<div class="row">
 
     
    <div class="large-9 columns" role="content">

<h1>All Tags</h1>

<ul id="tags">
  <% @tag.each do |tag| %>
    <li>
    <%= link_to tag.name, tag_path(tag) %>
    &nbsp
    <%= link_to "delete", tag_path(tag), :method => :delete %>
    </li>
  <% end %>
</ul>
 

app/views/tags/show.html.erb
<div class="row">
 
     
    <div class="large-9 columns" role="content">


<h1>Articles Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>